import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const plantSpecies = [
  // Popular Indoor Plants
  {
    commonName: "Monstera",
    scientificName: "Monstera deliciosa",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Weekly, when top inch of soil is dry",
    humidity: "High (60%+)",
    temperature: "65-85°F (18-29°C)",
    toxicity: "Toxic to pets and humans if ingested",
    careNotes: "Loves to climb, provide a moss pole for support. Wipe leaves to remove dust.",
  },
  {
    commonName: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    lightNeeds: "Low to bright indirect light",
    waterFrequency: "Every 2-3 weeks, allow soil to dry completely",
    humidity: "Low to average",
    temperature: "60-85°F (15-29°C)",
    toxicity: "Mildly toxic to pets",
    careNotes: "One of the easiest plants to care for. Excellent air purifier. Avoid overwatering.",
  },
  {
    commonName: "Pothos",
    scientificName: "Epipremnum aureum",
    lightNeeds: "Low to bright indirect light",
    waterFrequency: "Weekly, when soil is dry",
    humidity: "Average",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "Very forgiving and fast-growing. Can trail or climb. Propagates easily in water.",
  },
  {
    commonName: "Peace Lily",
    scientificName: "Spathiphyllum",
    lightNeeds: "Low to medium indirect light",
    waterFrequency: "Weekly, keep soil moist but not soggy",
    humidity: "High",
    temperature: "65-80°F (18-27°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "Droops dramatically when thirsty. Great air purifier. Will bloom in medium light.",
  },
  {
    commonName: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Weekly, when top 2 inches of soil are dry",
    humidity: "Average to high",
    temperature: "60-75°F (15-24°C)",
    toxicity: "Toxic to pets",
    careNotes: "Sensitive to changes. Avoid moving frequently. Wipe leaves to prevent dust buildup.",
  },
  {
    commonName: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Weekly, keep soil lightly moist",
    humidity: "Average",
    temperature: "55-80°F (13-27°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Produces baby plants (spiderettes) that can be propagated. Great for beginners.",
  },
  {
    commonName: "Rubber Plant",
    scientificName: "Ficus elastica",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Every 1-2 weeks, allow soil to dry between waterings",
    humidity: "Average",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Toxic to pets",
    careNotes: "Wipe leaves regularly for shine. Can grow quite tall indoors.",
  },
  {
    commonName: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    lightNeeds: "Low to bright indirect light",
    waterFrequency: "Every 2-3 weeks, allow soil to dry completely",
    humidity: "Low",
    temperature: "60-75°F (15-24°C)",
    toxicity: "Toxic if ingested",
    careNotes: "Extremely drought tolerant. Perfect for low-light spaces. Slow grower.",
  },
  {
    commonName: "Philodendron",
    scientificName: "Philodendron spp.",
    lightNeeds: "Medium to bright indirect light",
    waterFrequency: "Weekly, when top inch of soil is dry",
    humidity: "Average to high",
    temperature: "65-80°F (18-27°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "Easy to care for. Many varieties available. Can climb or trail.",
  },
  {
    commonName: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    lightNeeds: "Bright direct to indirect light",
    waterFrequency: "Every 2-3 weeks, allow soil to dry completely",
    humidity: "Low",
    temperature: "55-80°F (13-27°C)",
    toxicity: "Toxic to pets if ingested",
    careNotes: "Succulent with medicinal properties. Needs well-draining soil. Avoid overwatering.",
  },
  {
    commonName: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Keep soil consistently moist",
    humidity: "High (80%+)",
    temperature: "60-75°F (15-24°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Needs high humidity. Great for bathrooms. Mist regularly or use a humidifier.",
  },
  {
    commonName: "English Ivy",
    scientificName: "Hedera helix",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Weekly, keep soil evenly moist",
    humidity: "Average to high",
    temperature: "50-70°F (10-21°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "Trailing plant great for hanging baskets. Can be trained to climb.",
  },
  // Popular Outdoor Plants
  {
    commonName: "Rose",
    scientificName: "Rosa spp.",
    lightNeeds: "Full sun (6+ hours)",
    waterFrequency: "Deeply 2-3 times per week",
    humidity: "Average",
    temperature: "60-75°F (15-24°C)",
    toxicity: "Non-toxic (thorns can cause injury)",
    careNotes: "Prune in late winter. Watch for pests like aphids. Feed regularly during growing season.",
  },
  {
    commonName: "Lavender",
    scientificName: "Lavandula",
    lightNeeds: "Full sun",
    waterFrequency: "Every 1-2 weeks, drought tolerant once established",
    humidity: "Low",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Non-toxic",
    careNotes: "Needs well-draining soil. Prune after flowering. Attracts pollinators.",
  },
  {
    commonName: "Tomato",
    scientificName: "Solanum lycopersicum",
    lightNeeds: "Full sun (8+ hours)",
    waterFrequency: "Daily to every other day, keep soil consistently moist",
    humidity: "Average",
    temperature: "65-85°F (18-29°C)",
    toxicity: "Leaves toxic, fruit edible",
    careNotes: "Stake or cage for support. Remove suckers for larger fruit. Feed weekly.",
  },
  {
    commonName: "Basil",
    scientificName: "Ocimum basilicum",
    lightNeeds: "Full sun",
    waterFrequency: "Daily, keep soil moist",
    humidity: "Average",
    temperature: "70-90°F (21-32°C)",
    toxicity: "Non-toxic",
    careNotes: "Pinch off flower buds to encourage leaf growth. Harvest from top down.",
  },
  {
    commonName: "Hydrangea",
    scientificName: "Hydrangea macrophylla",
    lightNeeds: "Part sun to part shade",
    waterFrequency: "2-3 times per week, keep soil moist",
    humidity: "Average to high",
    temperature: "50-80°F (10-27°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "Soil pH affects flower color. Blue in acidic soil, pink in alkaline.",
  },
  {
    commonName: "Sunflower",
    scientificName: "Helianthus annuus",
    lightNeeds: "Full sun",
    waterFrequency: "Weekly, more in hot weather",
    humidity: "Average",
    temperature: "70-78°F (21-26°C)",
    toxicity: "Non-toxic",
    careNotes: "Annual plant. Support tall varieties. Great for pollinators.",
  },
  {
    commonName: "Mint",
    scientificName: "Mentha",
    lightNeeds: "Part sun to full sun",
    waterFrequency: "Keep soil consistently moist",
    humidity: "Average",
    temperature: "55-70°F (13-21°C)",
    toxicity: "Non-toxic (can be overwhelming for pets)",
    careNotes: "Spreads aggressively - best grown in containers. Harvest regularly.",
  },
  {
    commonName: "Succulent",
    scientificName: "Various species",
    lightNeeds: "Bright direct to indirect light",
    waterFrequency: "Every 2-4 weeks, allow to dry completely",
    humidity: "Low",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Varies by species",
    careNotes: "Need well-draining soil. Avoid overwatering. Many varieties available.",
  },
  {
    commonName: "Cactus",
    scientificName: "Cactaceae family",
    lightNeeds: "Bright direct light",
    waterFrequency: "Every 2-4 weeks in growing season, monthly in winter",
    humidity: "Low",
    temperature: "50-90°F (10-32°C)",
    toxicity: "Non-toxic (spines can cause injury)",
    careNotes: "Extremely drought tolerant. Need well-draining cactus soil mix.",
  },
  // More Indoor Plants
  {
    commonName: "Calathea",
    scientificName: "Calathea spp.",
    lightNeeds: "Low to medium indirect light",
    waterFrequency: "Weekly, keep soil moist but not soggy",
    humidity: "High (60%+)",
    temperature: "65-80°F (18-27°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Sensitive to tap water - use filtered or distilled. Leaves fold up at night.",
  },
  {
    commonName: "Dracaena",
    scientificName: "Dracaena marginata",
    lightNeeds: "Low to bright indirect light",
    waterFrequency: "Every 1-2 weeks, allow top soil to dry",
    humidity: "Average",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Toxic to pets",
    careNotes: "Tolerates neglect. Sensitive to fluoride in tap water.",
  },
  {
    commonName: "Bird of Paradise",
    scientificName: "Strelitzia reginae",
    lightNeeds: "Bright direct to indirect light",
    waterFrequency: "Weekly, allow top inch to dry",
    humidity: "Average to high",
    temperature: "65-80°F (18-27°C)",
    toxicity: "Mildly toxic",
    careNotes: "Needs lots of light to bloom indoors. Can grow quite large.",
  },
  {
    commonName: "String of Pearls",
    scientificName: "Senecio rowleyanus",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Every 2 weeks, allow to dry between waterings",
    humidity: "Low",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "Trailing succulent. Avoid overwatering. Needs well-draining soil.",
  },
  {
    commonName: "Chinese Evergreen",
    scientificName: "Aglaonema",
    lightNeeds: "Low to medium indirect light",
    waterFrequency: "Every 1-2 weeks",
    humidity: "Average to high",
    temperature: "65-80°F (18-27°C)",
    toxicity: "Toxic to pets",
    careNotes: "Very adaptable. Many colorful varieties. Great for low-light spaces.",
  },
  {
    commonName: "Jade Plant",
    scientificName: "Crassula ovata",
    lightNeeds: "Bright indirect to direct light",
    waterFrequency: "Every 2-3 weeks, allow soil to dry",
    humidity: "Low",
    temperature: "55-75°F (13-24°C)",
    toxicity: "Toxic to pets",
    careNotes: "Succulent that can live for decades. Needs well-draining soil.",
  },
  {
    commonName: "Prayer Plant",
    scientificName: "Maranta leuconeura",
    lightNeeds: "Low to bright indirect light",
    waterFrequency: "Weekly, keep soil moist",
    humidity: "High",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Leaves fold up at night like praying hands. Needs humidity.",
  },
  {
    commonName: "Croton",
    scientificName: "Codiaeum variegatum",
    lightNeeds: "Bright indirect to direct light",
    waterFrequency: "Weekly, keep soil moist",
    humidity: "High",
    temperature: "60-85°F (15-29°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "More light = more colorful leaves. Sensitive to cold drafts.",
  },
  {
    commonName: "Peperomia",
    scientificName: "Peperomia spp.",
    lightNeeds: "Medium to bright indirect light",
    waterFrequency: "Every 1-2 weeks, allow to dry between waterings",
    humidity: "Average",
    temperature: "55-80°F (13-27°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Compact plants perfect for small spaces. Many varieties available.",
  },
  {
    commonName: "Parlor Palm",
    scientificName: "Chamaedorea elegans",
    lightNeeds: "Low to bright indirect light",
    waterFrequency: "Weekly, keep soil lightly moist",
    humidity: "Average to high",
    temperature: "65-80°F (18-27°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Slow growing. One of the best palms for indoor growing.",
  },
  // Outdoor Flowering Plants
  {
    commonName: "Petunia",
    scientificName: "Petunia × atkinsiana",
    lightNeeds: "Full sun",
    waterFrequency: "Daily, keep soil moist",
    humidity: "Average",
    temperature: "60-75°F (15-24°C)",
    toxicity: "Non-toxic",
    careNotes: "Annual flowering plant. Deadhead spent blooms for continuous flowering.",
  },
  {
    commonName: "Marigold",
    scientificName: "Tagetes",
    lightNeeds: "Full sun",
    waterFrequency: "Weekly, drought tolerant once established",
    humidity: "Average",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Non-toxic",
    careNotes: "Annual. Repels some garden pests. Deadhead for more blooms.",
  },
  {
    commonName: "Geranium",
    scientificName: "Pelargonium",
    lightNeeds: "Full sun to part sun",
    waterFrequency: "When top inch of soil is dry",
    humidity: "Average",
    temperature: "55-75°F (13-24°C)",
    toxicity: "Toxic to pets",
    careNotes: "Great for containers. Pinch back for bushier growth.",
  },
  {
    commonName: "Dahlia",
    scientificName: "Dahlia pinnata",
    lightNeeds: "Full sun",
    waterFrequency: "2-3 times per week, keep soil moist",
    humidity: "Average",
    temperature: "60-75°F (15-24°C)",
    toxicity: "Non-toxic",
    careNotes: "Tuberous perennial. Stake tall varieties. Dig up tubers in cold climates.",
  },
  // Herbs and Edibles
  {
    commonName: "Rosemary",
    scientificName: "Salvia rosmarinus",
    lightNeeds: "Full sun",
    waterFrequency: "Every 1-2 weeks, allow to dry between waterings",
    humidity: "Low",
    temperature: "55-80°F (13-27°C)",
    toxicity: "Non-toxic",
    careNotes: "Mediterranean herb. Needs good drainage. Can be grown indoors with enough light.",
  },
  {
    commonName: "Cilantro",
    scientificName: "Coriandrum sativum",
    lightNeeds: "Part sun to full sun",
    waterFrequency: "Keep soil consistently moist",
    humidity: "Average",
    temperature: "50-85°F (10-29°C)",
    toxicity: "Non-toxic",
    careNotes: "Bolts quickly in heat. Succession plant for continuous harvest.",
  },
  {
    commonName: "Pepper Plant",
    scientificName: "Capsicum annuum",
    lightNeeds: "Full sun (6-8 hours)",
    waterFrequency: "Regular, keep soil evenly moist",
    humidity: "Average",
    temperature: "70-90°F (21-32°C)",
    toxicity: "Fruit edible, leaves mildly toxic",
    careNotes: "Many varieties from sweet to hot. Feed regularly when fruiting.",
  },
  {
    commonName: "Strawberry",
    scientificName: "Fragaria × ananassa",
    lightNeeds: "Full sun",
    waterFrequency: "Regular, keep soil moist",
    humidity: "Average",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Non-toxic",
    careNotes: "Perennial fruit. Remove runners for larger fruit. Mulch in winter.",
  },
  // Additional Popular Plants
  {
    commonName: "Orchid (Phalaenopsis)",
    scientificName: "Phalaenopsis spp.",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Weekly, water when roots are silver",
    humidity: "High (50-70%)",
    temperature: "65-80°F (18-27°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Use orchid bark, not soil. Ice cube watering method works well.",
  },
  {
    commonName: "Anthurium",
    scientificName: "Anthurium andraeanum",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Weekly, keep soil slightly moist",
    humidity: "High",
    temperature: "65-85°F (18-29°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "Long-lasting flowers. Needs high humidity. Wipe leaves regularly.",
  },
  {
    commonName: "Hoya",
    scientificName: "Hoya carnosa",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Every 1-2 weeks, allow to dry between waterings",
    humidity: "Average to high",
    temperature: "60-85°F (15-29°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Trailing or climbing plant. Produces fragrant waxy flowers when mature.",
  },
  {
    commonName: "Fern (Maidenhair)",
    scientificName: "Adiantum raddianum",
    lightNeeds: "Bright indirect light, no direct sun",
    waterFrequency: "Keep soil consistently moist",
    humidity: "High (60%+)",
    temperature: "60-75°F (15-24°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Delicate fronds need high humidity. Great for terrariums or bathrooms.",
  },
  {
    commonName: "Swiss Cheese Plant",
    scientificName: "Monstera adansonii",
    lightNeeds: "Bright indirect light",
    waterFrequency: "Weekly, when top inch is dry",
    humidity: "High",
    temperature: "65-80°F (18-27°C)",
    toxicity: "Toxic to pets and humans",
    careNotes: "Smaller than Monstera deliciosa. Can climb or trail. Fast grower.",
  },
  {
    commonName: "Dieffenbachia",
    scientificName: "Dieffenbachia seguine",
    lightNeeds: "Low to bright indirect light",
    waterFrequency: "Weekly, keep soil moist",
    humidity: "Average to high",
    temperature: "65-75°F (18-24°C)",
    toxicity: "Highly toxic - causes mouth numbness",
    careNotes: "Also called Dumb Cane. Handle with care. Large decorative leaves.",
  },
  {
    commonName: "Cast Iron Plant",
    scientificName: "Aspidistra elatior",
    lightNeeds: "Low light",
    waterFrequency: "Every 1-2 weeks",
    humidity: "Average",
    temperature: "50-85°F (10-29°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Nearly indestructible. Perfect for dark corners. Very slow grower.",
  },
  {
    commonName: "Ponytail Palm",
    scientificName: "Beaucarnea recurvata",
    lightNeeds: "Bright indirect to direct light",
    waterFrequency: "Every 2-3 weeks, allow to dry completely",
    humidity: "Low",
    temperature: "60-80°F (15-27°C)",
    toxicity: "Non-toxic to pets",
    careNotes: "Not a true palm. Stores water in its trunk. Drought tolerant.",
  },
];

async function main() {
  console.log("Seeding plant species data...");

  for (const species of plantSpecies) {
    await prisma.plantSpecies.upsert({
      where: {
        id: species.commonName.toLowerCase().replace(/\s+/g, "-").replace(/[()]/g, "")
      },
      update: species,
      create: {
        id: species.commonName.toLowerCase().replace(/\s+/g, "-").replace(/[()]/g, ""),
        ...species,
      },
    });
    console.log(`  ✓ ${species.commonName}`);
  }

  console.log(`\nSeeded ${plantSpecies.length} plant species!`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
